version: "2.2"
services:

  auth:
    image: blade-auth:1.2
    container_name: auth
    ports:
      - "9871:9871"
    links:
      - nacos
    depends_on:
      nacos:
        condition: service_healthy
    volumes:
      - ./blade-auth/logs:/blade/auth/target/blade/log
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xms256m -Xmx256m -Xmn16m -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC -XX:+UseCMSCompactAtFullCollection -XX:CMSInitiatingOccupancyFraction=70 -XX:+CMSParallelRemarkEnabled -XX:SoftRefLRUPolicyMSPerMB=0 -XX:+CMSClassUnloadingEnabled -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M

  gateway:
    image: blade-gateway:1.7
    container_name: gateway
    ports:
      - "9872:9872"
    links:
      - nacos
    depends_on:
      nacos:
        condition: service_healthy
    volumes:
      - ./blade-gateway/logs:/blade/gateway/target/blade/log
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xms64m -Xmx64m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC

  message:
    image: blade-message:1.2
    container_name: message
    ports:
      - "9873:9873"
      - "5883:5883"
    links:
      - nacos
    depends_on:
      nacos:
        condition: service_healthy
    volumes:
      - ./blade-message/logs:/blade/message/target/blade/log
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xms256m -Xmx256m -Xmn16m -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC -XX:+UseCMSCompactAtFullCollection -XX:CMSInitiatingOccupancyFraction=70 -XX:+CMSParallelRemarkEnabled -XX:SoftRefLRUPolicyMSPerMB=0 -XX:+CMSClassUnloadingEnabled -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M

  mjkj:
    image: blade-mjkj:1.2
    container_name: mjkj
    ports:
      - "9874:9874"
    links:
      - nacos
    depends_on:
      nacos:
        condition: service_healthy
    volumes:
      - ./blade-mjkj/logs:/blade/mjkj/target/blade/log
      - ./blade-mjkj/data:/blade/mjkj/data
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xms256m -Xmx256m -Xmn16m -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC -XX:+UseCMSCompactAtFullCollection -XX:CMSInitiatingOccupancyFraction=70 -XX:+CMSParallelRemarkEnabled -XX:SoftRefLRUPolicyMSPerMB=0 -XX:+CMSClassUnloadingEnabled -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M

  system:
    image: blade-system:1.2
    container_name: system
    links:
      - nacos
    depends_on:
      nacos:
        condition: service_healthy
    ports:
      - "9875:9875"
    volumes:
      - ./blade-system/logs:/blade/system/target/blade/log
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xms256m -Xmx256m -Xmn16m -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC -XX:+UseCMSCompactAtFullCollection -XX:CMSInitiatingOccupancyFraction=70 -XX:+CMSParallelRemarkEnabled -XX:SoftRefLRUPolicyMSPerMB=0 -XX:+CMSClassUnloadingEnabled -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M

  user:
    image: blade-user:1.2
    container_name: user
    links:
      - nacos
    depends_on:
      nacos:
        condition: service_healthy
    ports:
      - "9876:9876"
    volumes:
      - ./blade-user/logs:/blade/user/target/blade/log
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xms256m -Xmx256m -Xmn16m -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC -XX:+UseCMSCompactAtFullCollection -XX:CMSInitiatingOccupancyFraction=70 -XX:+CMSParallelRemarkEnabled -XX:SoftRefLRUPolicyMSPerMB=0 -XX:+CMSClassUnloadingEnabled -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/log:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true
    environment:
      - TZ=Asia/Shanghai

  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    restart: always
    env_file:
      - ./nacos/nacos-standlone-mysql.env
    volumes:
      - ./nacos/logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    links:
      - mysql
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8848/nacos/v1/console/health/readiness" ]
      interval: 5s
      timeout: 10s
      retries: 10

  mysql:
    image: mysql:8.0.22
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql8.0.22/conf.d:/etc/mysql/conf.d
      - ./mysql8.0.22/data:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
    security_opt:
      - seccomp:unconfined
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 3

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server /etc/conf/redis.conf
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/etc/conf/redis.conf
    privileged: true
    environment:
      - TZ=Asia/Shanghai

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9099:9099"
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      TZ: Asia/Shanghai
    command: server --address ":9099" --console-address ":9000" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
